### ISSUE TITLE
Doesn't Work Well With SquareLauncher2

### ISSUE THREAD

**Issue by Xarcell** [BaronKiko/LauncherHijackV2#2]
It seems that it only allows horizontal scrolling. SquareLauncher2 mimics Windows10 with vertical scrolling.

**Comment by Xarcell** [comment]
NVM, I fixed it by simply turning off tablet mode in SquareLauncher2 settings.

**Comment by BaronKiko** [comment]
I have literally no idea what you mean by that bug but to clarify all this app does is open your launcher of choice. Akin to going to the fire launcher and opening you alternative launcher. So any bugs in the launcher are out of my control.

**Comment by Xarcell** [comment]
It was my mistake. It is not a bug, but a setting in the launcher.

**Comment by BaronKiko** [comment]
Good you got it sorted
