### ISSUE TITLE
Hijack launcher V.2 has a problem

### ISSUE THREAD

**Issue by joselopezcap** [BaronKiko/LauncherHijackV2#3]
The hijack launcher app has a problem which is whenever you press the home button the fire launcher flashes then the Nova launcher appears .
I'm am using the fire HD 8 tablet ( 6th gen)
Here's​ a link of a video of the problem to help u
https://youtu.be/Ek8qvbGn7QY

Please fix this problem thank you

**Comment by BaronKiko** [comment]
Unfortunately this a side effect of how the app functions. Whenever it detects the fire launcher opening it opens the app switcher, to remove restrictions on launching another app, then launches your launcher of choice.
The best I could do is throwing up a black screen while it's changing however that's harder than it sounds so I never implemented it and frankly I doubt I will ever get around to it as it doesn't make much difference.
Hope that explains the issue, and while I currently have no plans to implement it the code is there for anybody else to give it a go.
