### ISSUE TITLE
Not working on Fire OS 5.4.0.0

### ISSUE THREAD

**Issue by jamesevickery** [BaronKiko/LauncherHijackV2#4]
1. Installed via adb from apk
2. Opened app, clicked Nova, tried to set as default
3. Hit the home button

Tablet went back to Fire launcher as usual

LauncherHijackV2 version 2.1
FireOS version 5.4.0.0 (built 1st June 2017)

**Comment by BaronKiko** [comment]
Make sure you enabled it in accessibility settings. Please read the instructions bofore posting a bug.

**Comment by jamesevickery** [comment]
@BaronKiko Where are the instructions? Couldn't find them on this repo

**Comment by BaronKiko** [comment]
They barely count as instructions, just one step. They were and still are on the XDA thread but I have updated the read me for you with all the info anybody could need.

**Comment by jamesevickery** [comment]
@BaronKiko Thanks :+1:
