### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by watkinsmatthewp** [BaronKiko/LauncherHijackV2#5]
I performed the following on the Kindle Fire HD 8 (7th generation) I got today. It's running Fire OS 5.4.0.0. I have enabled installing apps from unknown sources, then downloaded the launcher hijack apk. When I try to open it, I am greeted with the same installation screen as all the other apps I've sideloaded, but my tablet won't register my press on the install button.

Is Amazon maybe blocking the installation of your app? That would really stink-- I hate the Fire OS launcher... :(

![screenshot_2017-07-16-22-05-26](https://user-images.githubusercontent.com/3808901/28253603-80c2c454-6a73-11e7-973c-95a8ef7f1045.png)

**Comment by watkinsmatthewp** [comment]
I installed the remaining 7 Amazon updates to the Fire tablet and it allowed me to install and everything's great after that. There's the flicker of seeing the Fire launcher for a brief moment, but that's a small price to pay for having a clean home screen. Thanks!

**Comment by BaronKiko** [comment]
Odd bug but I'm glad you got around it. If anybody else encounters this issue then you can just install through and using adb install PATH_TO_APK
