### ISSUE TITLE
Total Launcher

### ISSUE THREAD

**Issue by purdychelle** [BaronKiko/LauncherHijackV2#6]
When I open Launcher Hijack, it allows me to choose Total Launcher as the Launcher to use, but when I go to Home, it defaults to the Fire launcher. I tried restarting and waiting 10 seconds and tapping on Home again to no avail. Does it not work with Total Launcher?

**Comment by BaronKiko** [comment]
I cant try atm but make sure you have followed all instructions on the XDA forum. I'm guessing you hadn't enabled the service in settings

**Comment by ViciousV826** [comment]
I am having an issue where I can not download the LauncherHijack file into my device. It will give me the prompt To Install It But When I Click The Install Button It Does Nothing. I Can However Download It On Chrome. Please Help

**Comment by BaronKiko** [comment]
I'm assuming total launcher works fine so I'm going to close this issue.
@viciousV826 1) don't post on a preexisting issue. 2) search the issues that already have solutions, you will find your answer as I answered it the other day.
