### ISSUE TITLE
Fire HD 8 v 5.4.0.0 does not have "Detect Home Button" option anymore

### ISSUE THREAD

**Issue by pdhinco** [BaronKiko/LauncherHijackV2#8]
The subject says it all - is "Detect Home button" ON by default in 5.4.0.0, or have you found a workaround?  I just recvd a Fire HD 8 (7th Gen), and got upgraded before I could stop it.

I'd try it, but I'm a noob, and don't know if there is risk of permanent bricking. . .

Thanks in advance, Paul

**Comment by BaronKiko** [comment]
Don't open an issue for a question, use the xda forum. There is no risk of bricking it's just an app so if you don't like it just uninstall it. Follow instructions and do some reading, all your answers will be answered.
